apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner-whisper-workshop
spec:
  text: "Red Hat OpenShift AI — Real-Time AI Translation with Whisper"
  location: BannerTop
  color: '#FFF'
  backgroundColor: '#0066CC'
